### PR TITLE
Update to work with MacOS

### LINKED ISSUE #76: Cannot install dependencies on M series Mac
Several installed libraries are exclusive to x86_64, Linux, or both, [for example](https://github.com/openai/triton?tab=readme-ov-file#compatibility). Luckily these are dependencies of dependencies, so we could switch to a package management system like Poetry, [which supports conditionally installing dependencies based on the platform](https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies). While I don't foresee people running the server on a Mac, it might be good for getting more developers on board.

Specifically, it appears that `torch==2.2.0` is not well supported for M series Macs. One solution, for now, is just to install `torch==2.0.0`, ignore `torchvision==0.17.0` and `triton==2.0.0`, and let `pip` figure out the right dependencies. However, `pip freeze` will always output every installed package making it difficult to maintain. 

Another reason to pivot to a more advanced package management system is that, unless the user wants to use embeddings, there's no reason to install all the machine learning stuff on a person's machine.

### PR DESCRIPTION
**Pull request by jwmatthews**
Fixes #76

### CODE REVIEW

**Comment by jwmatthews** [comment]
@JonahSussman @savitharaghunathan please see if this works for you in a clean venv.

@jmontleon showed how we can include or ignore specific requirements for 'darwin'.

I tried this on MacOS arm64 with python 3.11 and python 3.12 and looking good.

**Comment by JonahSussman** [comment]
Don't have an arm mac to test but lgtm

**Review by jmontleon — APPROVED** [review]
ACK

**Comment by jwmatthews** [comment]
@JonahSussman sorry, I meant please try these requirements.txt out on your Linux box.

In theory this same requirements.txt should work on Linux or Mac.

**Comment by JonahSussman** [comment]
Should have used the logic part of my brain! Yeah, there are no issues using it on my x86_64 machine

**Review by JonahSussman — APPROVED** [review]

**Review by savitharaghunathan — APPROVED** [review]
Tested the changes on my macOS/intel and it works.

**Pull request merged**
