### PR TITLE
Make server WSGI compatible 

### PR DESCRIPTION
**Pull request by fabianvf**
This allows us to run it with Gunicorn and multiple workers, to better
handle concurrent requests.

Also Update client to make requests in parallel

Related to #100 

Blocked by #93

### CODE REVIEW

**Comment by fabianvf** [comment]
Just look at the last two commits for review, the others are from #93

**Review by jwmatthews — APPROVED** [review]
"ibm/granite-13b-chat-v2":  completed in 19:49.16 total
Great improvement @fabianvf 

LGTM to merge.

I saw 2 things while testing, don't think it needs to block the PR:

- On CTRL-C of `make run-server` I'm seeing Python crash, unsure if this is MacOS only behavior.  
- The output to server console shows a message that looks like some workers are having problems on initialization, then maybe they get restarted are OK

          [2024-03-25 19:27:22 -0400] [11615] [INFO] Booting worker with pid: 11615
          [2024-03-25 19:27:22 -0400] [11616] [INFO] Booting worker with pid: 11616
          [2024-03-25 19:27:24 -0400] [11601] [ERROR] Worker (pid:11625) exited with code 255
          [2024-03-25 19:27:24 -0400] [11601] [ERROR] Worker (pid:11625) exited with code 255.

**Comment by jwmatthews** [comment]
@fabianvf just a FYI, not blocking this PR, i saw some errors when running a longer migration against mixtral, ran for ~2 hours 20 minutes, looked like many issues with backend (IBM serving mixtral side).  

https://github.com/konveyor-ecosystem/kai/issues/109

**Comment by fabianvf** [comment]
@jwmatthews did the workers recover and the subsequent request succeed or was it broken enough that the demo script failed?

**Comment by fabianvf** [comment]
Ah, I accidentally committed the timeout bump for the requests so it's higher than the worker. The worker timed out after 20 minutes of working on a request I think. I can fix that, but the issue of the mega long requests probably needs the smooshing stuff that Jonah is working on

**Comment by jwmatthews** [comment]
> @jwmatthews did the workers recover and the subsequent request succeed or was it broken enough that the demo script failed?

Demo script failed.

**Comment by jwmatthews** [comment]
@fabianvf  I'm good to merge this now and we can investigate/fix edge cases later.
I'd just ask if you can fix the small trunk lint issues that'd be nice before merging.

**Pull request merged**
