### PR TITLE
Added prompt tweaker notebook

### PR DESCRIPTION
**Pull request by JonahSussman**

### CODE REVIEW

**Review by jmontleon — APPROVED** [review]
ACK. Works for me.

**Comment by jmontleon** [comment]
Actually it looks like changes to the PREAMBLE in the notebook aren't taking effect. It looks like it's being taken from:
kai/kai/data/templates/mf_preamble.txt.

Editing that file and restarting changes the prompt.

**Comment by JonahSussman** [comment]
Whoops! Will fix!

**Comment by JonahSussman** [comment]
@jmontleon Fixed

**Comment by jmontleon** [comment]
ACK, that fixed it!

**Pull request merged**
